/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Swagger
 * Swagger api description
 * OpenAPI spec version: 1.0
 */
export interface PingReqDto {
  message?: string;
}

export interface PingResDtoOutput {
  message?: string;
  time: string;
}

export type appControllerGetHelloResponse200 = {
  data: void;
  status: 200;
};

export type appControllerGetHelloResponseSuccess =
  appControllerGetHelloResponse200 & {
    headers: Headers;
  };
export type appControllerGetHelloResponse =
  appControllerGetHelloResponseSuccess;

export const getAppControllerGetHelloUrl = () => {
  return `/`;
};

export const appControllerGetHello = async (
  options?: RequestInit,
): Promise<appControllerGetHelloResponse> => {
  const res = await fetch(getAppControllerGetHelloUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetHelloResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as appControllerGetHelloResponse;
};

export type appControllerUsersResponse200 = {
  data: void;
  status: 200;
};

export type appControllerUsersResponseSuccess =
  appControllerUsersResponse200 & {
    headers: Headers;
  };
export type appControllerUsersResponse = appControllerUsersResponseSuccess;

export const getAppControllerUsersUrl = () => {
  return `/users`;
};

export const appControllerUsers = async (
  options?: RequestInit,
): Promise<appControllerUsersResponse> => {
  const res = await fetch(getAppControllerUsersUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerUsersResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as appControllerUsersResponse;
};

export type appControllerPingResponseDefault = {
  data: PingResDtoOutput;
  status: number;
};
export type appControllerPingResponseError =
  appControllerPingResponseDefault & {
    headers: Headers;
  };

export type appControllerPingResponse = appControllerPingResponseError;

export const getAppControllerPingUrl = () => {
  return `/ping`;
};

export const appControllerPing = async (
  pingReqDto: PingReqDto,
  options?: RequestInit,
): Promise<appControllerPingResponse> => {
  const res = await fetch(getAppControllerPingUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(pingReqDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerPingResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as appControllerPingResponse;
};
